-- ============================================
-- LanternELL Product Catalog Seed
-- 45 single packs + 5 bundles + 1 membership
-- Generated: 2026-03-08 03:27:39.356
-- ============================================

BEGIN TRANSACTION;

-- === Single Packs (45) ===
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p985jnxu', 'classroom-objects-vocabulary-pack-k-2-en-es', 'Classroom Objects — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Classroom Objects" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9fwxe21', 'colors-vocabulary-pack-k-2-en-es', 'Colors — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Colors" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9r60mpc', 'numbers-1-20-vocabulary-pack-k-2-en-es', 'Numbers 1-20 — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Numbers 1-20" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p91z9api', 'shapes-vocabulary-pack-k-2-en-es', 'Shapes — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Shapes" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p99ovlvg', 'animals-vocabulary-pack-k-2-en-es', 'Animals — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Animals" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9te6d37', 'food-vocabulary-pack-k-2-en-es', 'Food — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Food" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9j137ff', 'family-members-vocabulary-pack-k-2-en-es', 'Family Members — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Family Members" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9fpiuab', 'body-parts-vocabulary-pack-k-2-en-es', 'Body Parts — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Body Parts" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p95efbrb', 'weather-and-seasons-vocabulary-pack-k-2-en-es', 'Weather & Seasons — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Weather & Seasons" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9tx86c3', 'clothes-vocabulary-pack-k-2-en-es', 'Clothes — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Clothes" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9nayzm7', 'classroom-furniture-classroom-labels-k-2-en-es', 'Classroom Furniture — Classroom Labels (K-2, EN-ES)', 'Bilingual classroom labels in full-size and small formats for "Classroom Furniture" — print, cut, and display in your K-2 classroom. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p98a143k', 'school-supplies-classroom-labels-k-2-en-es', 'School Supplies — Classroom Labels (K-2, EN-ES)', 'Bilingual classroom labels in full-size and small formats for "School Supplies" — print, cut, and display in your K-2 classroom. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9er6e8b', 'classroom-areas-classroom-labels-k-2-en-es', 'Classroom Areas — Classroom Labels (K-2, EN-ES)', 'Bilingual classroom labels in full-size and small formats for "Classroom Areas" — print, cut, and display in your K-2 classroom. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9e88j70', 'days-and-months-classroom-labels-k-2-en-es', 'Days & Months — Classroom Labels (K-2, EN-ES)', 'Bilingual classroom labels in full-size and small formats for "Days & Months" — print, cut, and display in your K-2 classroom. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9mmehyy', 'time-and-clock-classroom-labels-k-2-en-es', 'Time & Clock — Classroom Labels (K-2, EN-ES)', 'Bilingual classroom labels in full-size and small formats for "Time & Clock" — print, cut, and display in your K-2 classroom. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9mgg8lt', 'basic-greetings-sentence-frames-k-2-en-es', 'Basic Greetings — Sentence Frames (K-2, EN-ES)', 'Bilingual sentence frame cards, dialogue strips, speaking prompts, and writing practice for "Basic Greetings" — designed for K-2 ELL newcomers. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9ntw2bj', 'asking-for-help-sentence-frames-k-2-en-es', 'Asking for Help — Sentence Frames (K-2, EN-ES)', 'Bilingual sentence frame cards, dialogue strips, speaking prompts, and writing practice for "Asking for Help" — designed for K-2 ELL newcomers. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9xw1kbr', 'expressing-feelings-sentence-frames-k-2-en-es', 'Expressing Feelings — Sentence Frames (K-2, EN-ES)', 'Bilingual sentence frame cards, dialogue strips, speaking prompts, and writing practice for "Expressing Feelings" — designed for K-2 ELL newcomers. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9srsnkh', 'classroom-instructions-sentence-frames-k-2-en-es', 'Classroom Instructions — Sentence Frames (K-2, EN-ES)', 'Bilingual sentence frame cards, dialogue strips, speaking prompts, and writing practice for "Classroom Instructions" — designed for K-2 ELL newcomers. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9yk5n6d', 'sharing-and-taking-turns-sentence-frames-k-2-en-es', 'Sharing & Taking Turns — Sentence Frames (K-2, EN-ES)', 'Bilingual sentence frame cards, dialogue strips, speaking prompts, and writing practice for "Sharing & Taking Turns" — designed for K-2 ELL newcomers. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9brg3g4', 'transportation-vocabulary-pack-k-2-en-es', 'Transportation — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Transportation" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p93scn97', 'places-in-community-vocabulary-pack-k-2-en-es', 'Places in Community — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Places in Community" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p94nutub', 'feelings-and-emotions-vocabulary-pack-k-2-en-es', 'Feelings & Emotions — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Feelings & Emotions" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9f5pwk0', 'action-verbs-vocabulary-pack-k-2-en-es', 'Action Verbs — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Action Verbs" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9eox9rq', 'opposites-vocabulary-pack-k-2-en-es', 'Opposites — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Opposites" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9uwuy2f', 'science-vocabulary-vocabulary-pack-3-5-en-es', 'Science Vocabulary — Vocabulary Pack (3-5, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Science Vocabulary" — designed for 3-5 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p955suib', 'math-vocabulary-vocabulary-pack-3-5-en-es', 'Math Vocabulary — Vocabulary Pack (3-5, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Math Vocabulary" — designed for 3-5 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p90iydi5', 'social-studies-vocabulary-pack-3-5-en-es', 'Social Studies — Vocabulary Pack (3-5, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Social Studies" — designed for 3-5 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9dd50dz', 'reading-and-writing-vocabulary-pack-3-5-en-es', 'Reading & Writing — Vocabulary Pack (3-5, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Reading & Writing" — designed for 3-5 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 899, 'premium', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9wu8b1i', 'health-and-safety-vocabulary-pack-3-5-en-es', 'Health & Safety — Vocabulary Pack (3-5, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Health & Safety" — designed for 3-5 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p947vfbw', 'geography-and-maps-vocabulary-pack-3-5-en-es', 'Geography & Maps — Vocabulary Pack (3-5, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Geography & Maps" — designed for 3-5 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9ir00yf', 'technology-and-computers-vocabulary-pack-3-5-en-es', 'Technology & Computers — Vocabulary Pack (3-5, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Technology & Computers" — designed for 3-5 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p96hezqf', 'arts-and-music-vocabulary-pack-3-5-en-es', 'Arts & Music — Vocabulary Pack (3-5, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Arts & Music" — designed for 3-5 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9z1raet', 'academic-discussion-sentence-frames-3-5-en-es', 'Academic Discussion — Sentence Frames (3-5, EN-ES)', 'Bilingual sentence frame cards, dialogue strips, speaking prompts, and writing practice for "Academic Discussion" — designed for 3-5 ELL newcomers. English-Spanish.', 'single', 899, 'premium', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p97g7ff8', 'writing-prompts-and-responses-sentence-frames-3-5-en-es', 'Writing Prompts & Responses — Sentence Frames (3-5, EN-ES)', 'Bilingual sentence frame cards, dialogue strips, speaking prompts, and writing practice for "Writing Prompts & Responses" — designed for 3-5 ELL newcomers. English-Spanish.', 'single', 899, 'premium', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p94u9xqb', 'book-reports-and-reading-logs-sentence-frames-3-5-en-es', 'Book Reports & Reading Logs — Sentence Frames (3-5, EN-ES)', 'Bilingual sentence frame cards, dialogue strips, speaking prompts, and writing practice for "Book Reports & Reading Logs" — designed for 3-5 ELL newcomers. English-Spanish.', 'single', 899, 'premium', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9gnhvkr', 'science-lab-labels-classroom-labels-3-5-en-es', 'Science Lab Labels — Classroom Labels (3-5, EN-ES)', 'Bilingual classroom labels in full-size and small formats for "Science Lab Labels" — print, cut, and display in your 3-5 classroom. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9mn1mkd', 'academic-vocabulary-vocabulary-pack-6-8-en-es', 'Academic Vocabulary — Vocabulary Pack (6-8, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Academic Vocabulary" — designed for 6-8 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 899, 'premium', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9xyyf25', 'lab-reports-and-scientific-method-vocabulary-pack-6-8-en-es', 'Lab Reports & Scientific Method — Vocabulary Pack (6-8, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Lab Reports & Scientific Method" — designed for 6-8 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 899, 'premium', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p96vv3dv', 'career-and-life-skills-vocabulary-pack-6-8-en-es', 'Career & Life Skills — Vocabulary Pack (6-8, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Career & Life Skills" — designed for 6-8 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9d3lra2', 'literary-analysis-sentence-frames-6-8-en-es', 'Literary Analysis — Sentence Frames (6-8, EN-ES)', 'Bilingual sentence frame cards, dialogue strips, speaking prompts, and writing practice for "Literary Analysis" — designed for 6-8 ELL newcomers. English-Spanish.', 'single', 899, 'premium', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9fbtasw', 'research-and-citation-sentence-frames-6-8-en-es', 'Research & Citation — Sentence Frames (6-8, EN-ES)', 'Bilingual sentence frame cards, dialogue strips, speaking prompts, and writing practice for "Research & Citation" — designed for 6-8 ELL newcomers. English-Spanish.', 'single', 899, 'premium', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p99hhkup', 'welcome-letter-parent-communication-k-2-en-es', 'Welcome Letter — Parent Communication (K-2, EN-ES)', 'Bilingual parent communication templates for "Welcome Letter" — ready to print and send home. Covers English and Spanish for K-2 classrooms.', 'single', 399, 'standard', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9kfjk43', 'homework-note-parent-communication-k-2-en-es', 'Homework Note — Parent Communication (K-2, EN-ES)', 'Bilingual parent communication templates for "Homework Note" — ready to print and send home. Covers English and Spanish for K-2 classrooms.', 'single', 399, 'standard', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9cppyrq', 'progress-report-parent-communication-k-2-en-es', 'Progress Report — Parent Communication (K-2, EN-ES)', 'Bilingual parent communication templates for "Progress Report" — ready to print and send home. Covers English and Spanish for K-2 classrooms.', 'single', 399, 'standard', 1, '2026-03-08 03:27:39.356');

-- === Bundles (5) ===
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9oq4q7j', 'newcomer-starter-kit-bundle-en-es', 'Newcomer Starter Kit', 'Everything a newcomer student needs in their first weeks: classroom objects, colors, numbers, basic greetings, and asking for help. 5 printable packs, English-Spanish.', 'bundle', 1499, 'mini_bundle', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9pof8pi', 'classroom-essentials-labels-bundle-en-es', 'Classroom Essentials — Labels & Signs', 'Set up your bilingual classroom with all 5 label packs: furniture, supplies, areas, days & months, and time. Print, cut, and display. English-Spanish.', 'bundle', 1499, 'mini_bundle', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9ykmop2', 'grade-3-5-academic-pack-bundle-en-es', 'Grade 3-5 Academic Pack', 'All 12 teaching packs designed for grades 3-5 — science, math, social studies, reading, writing, and academic discussion. English-Spanish.', 'bundle', 1499, 'mini_bundle', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9e13qjs', 'middle-school-newcomer-pack-bundle-en-es', 'Middle School Newcomer Pack', 'Academic vocabulary, literary analysis, research skills, and career readiness for grades 6-8 ELL newcomers. 5 printable packs, English-Spanish.', 'bundle', 1499, 'mini_bundle', 1, '2026-03-08 03:27:39.356');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p9dnia1k', 'complete-k8-ell-pack-bundle-en-es', 'Complete K-8 ELL Teaching Pack', 'All 45 printable teaching packs in one bundle — vocabulary, labels, sentence frames, and parent communication for K-8 ELL and bilingual classrooms. English-Spanish. Best value.', 'bundle', 2999, 'full_bundle', 1, '2026-03-08 03:27:39.356');

-- === Membership (1) ===
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at) VALUES ('prod_mmh6z1p996jqfa', 'all-access-membership', 'LanternELL All Access', 'Unlimited downloads of every pack in the LanternELL library. New packs added regularly. Cancel anytime.', 'membership', 900, 'monthly', 1, '2026-03-08 03:27:39.356');

-- === Bundle Resource Links ===
-- Bundle: Newcomer Starter Kit
-- product_resources link: bundle prod_mmh6z1p9oq4q7j -> single pack prod_mmh6z1p985jnxu (Classroom Objects)
-- product_resources link: bundle prod_mmh6z1p9oq4q7j -> single pack prod_mmh6z1p9fwxe21 (Colors)
-- product_resources link: bundle prod_mmh6z1p9oq4q7j -> single pack prod_mmh6z1p9r60mpc (Numbers 1-20)
-- product_resources link: bundle prod_mmh6z1p9oq4q7j -> single pack prod_mmh6z1p9mgg8lt (Basic Greetings)
-- product_resources link: bundle prod_mmh6z1p9oq4q7j -> single pack prod_mmh6z1p9ntw2bj (Asking for Help)
-- Bundle: Classroom Essentials — Labels & Signs
-- product_resources link: bundle prod_mmh6z1p9pof8pi -> single pack prod_mmh6z1p9nayzm7 (Classroom Furniture)
-- product_resources link: bundle prod_mmh6z1p9pof8pi -> single pack prod_mmh6z1p98a143k (School Supplies)
-- product_resources link: bundle prod_mmh6z1p9pof8pi -> single pack prod_mmh6z1p9er6e8b (Classroom Areas)
-- product_resources link: bundle prod_mmh6z1p9pof8pi -> single pack prod_mmh6z1p9e88j70 (Days & Months)
-- product_resources link: bundle prod_mmh6z1p9pof8pi -> single pack prod_mmh6z1p9mmehyy (Time & Clock)
-- Bundle: Grade 3-5 Academic Pack
-- product_resources link: bundle prod_mmh6z1p9ykmop2 -> single pack prod_mmh6z1p9uwuy2f (Science Vocabulary)
-- product_resources link: bundle prod_mmh6z1p9ykmop2 -> single pack prod_mmh6z1p955suib (Math Vocabulary)
-- product_resources link: bundle prod_mmh6z1p9ykmop2 -> single pack prod_mmh6z1p90iydi5 (Social Studies)
-- product_resources link: bundle prod_mmh6z1p9ykmop2 -> single pack prod_mmh6z1p9dd50dz (Reading & Writing)
-- product_resources link: bundle prod_mmh6z1p9ykmop2 -> single pack prod_mmh6z1p9wu8b1i (Health & Safety)
-- product_resources link: bundle prod_mmh6z1p9ykmop2 -> single pack prod_mmh6z1p947vfbw (Geography & Maps)
-- product_resources link: bundle prod_mmh6z1p9ykmop2 -> single pack prod_mmh6z1p9ir00yf (Technology & Computers)
-- product_resources link: bundle prod_mmh6z1p9ykmop2 -> single pack prod_mmh6z1p96hezqf (Arts & Music)
-- product_resources link: bundle prod_mmh6z1p9ykmop2 -> single pack prod_mmh6z1p9z1raet (Academic Discussion)
-- product_resources link: bundle prod_mmh6z1p9ykmop2 -> single pack prod_mmh6z1p97g7ff8 (Writing Prompts & Responses)
-- product_resources link: bundle prod_mmh6z1p9ykmop2 -> single pack prod_mmh6z1p94u9xqb (Book Reports & Reading Logs)
-- product_resources link: bundle prod_mmh6z1p9ykmop2 -> single pack prod_mmh6z1p9gnhvkr (Science Lab Labels)
-- Bundle: Middle School Newcomer Pack
-- product_resources link: bundle prod_mmh6z1p9e13qjs -> single pack prod_mmh6z1p9mn1mkd (Academic Vocabulary)
-- product_resources link: bundle prod_mmh6z1p9e13qjs -> single pack prod_mmh6z1p9xyyf25 (Lab Reports & Scientific Method)
-- product_resources link: bundle prod_mmh6z1p9e13qjs -> single pack prod_mmh6z1p96vv3dv (Career & Life Skills)
-- product_resources link: bundle prod_mmh6z1p9e13qjs -> single pack prod_mmh6z1p9d3lra2 (Literary Analysis)
-- product_resources link: bundle prod_mmh6z1p9e13qjs -> single pack prod_mmh6z1p9fbtasw (Research & Citation)
-- Bundle: Complete K-8 ELL Teaching Pack
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p985jnxu (Classroom Objects)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9fwxe21 (Colors)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9r60mpc (Numbers 1-20)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p91z9api (Shapes)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p99ovlvg (Animals)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9te6d37 (Food)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9j137ff (Family Members)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9fpiuab (Body Parts)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p95efbrb (Weather & Seasons)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9tx86c3 (Clothes)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9nayzm7 (Classroom Furniture)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p98a143k (School Supplies)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9er6e8b (Classroom Areas)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9e88j70 (Days & Months)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9mmehyy (Time & Clock)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9mgg8lt (Basic Greetings)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9ntw2bj (Asking for Help)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9xw1kbr (Expressing Feelings)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9srsnkh (Classroom Instructions)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9yk5n6d (Sharing & Taking Turns)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9brg3g4 (Transportation)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p93scn97 (Places in Community)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p94nutub (Feelings & Emotions)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9f5pwk0 (Action Verbs)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9eox9rq (Opposites)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9uwuy2f (Science Vocabulary)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p955suib (Math Vocabulary)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p90iydi5 (Social Studies)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9dd50dz (Reading & Writing)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9wu8b1i (Health & Safety)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p947vfbw (Geography & Maps)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9ir00yf (Technology & Computers)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p96hezqf (Arts & Music)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9z1raet (Academic Discussion)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p97g7ff8 (Writing Prompts & Responses)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p94u9xqb (Book Reports & Reading Logs)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9gnhvkr (Science Lab Labels)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9mn1mkd (Academic Vocabulary)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9xyyf25 (Lab Reports & Scientific Method)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p96vv3dv (Career & Life Skills)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9d3lra2 (Literary Analysis)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9fbtasw (Research & Citation)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p99hhkup (Welcome Letter)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9kfjk43 (Homework Note)
-- product_resources link: bundle prod_mmh6z1p9dnia1k -> single pack prod_mmh6z1p9cppyrq (Progress Report)

COMMIT;

-- ============================================
-- Summary:
--   Single packs: 45
--   Bundles: 5
--   Membership: 1
--   Total products: 51
-- ============================================
--
-- Price tier distribution (single packs):
--   plus: 18 packs × $5.99 = 107.82 total value
--   standard: 19 packs × $3.99 = 75.81 total value
--   premium: 8 packs × $8.99 = 71.92 total value