-- ============================================
-- LanternELL Product Catalog Seed
-- 30 single packs + 3 bundles + 1 membership
-- Generated: 2026-03-08 03:18:42.958
-- ============================================

BEGIN TRANSACTION;

-- === Single Packs (30) ===
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtbujutwl', 'classroom-objects-vocabulary-pack-k-2-en-es', 'Classroom Objects — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Classroom Objects" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtc22xiry', 'colors-vocabulary-pack-k-2-en-es', 'Colors — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Colors" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtcfoujlk', 'numbers-1-20-vocabulary-pack-k-2-en-es', 'Numbers 1-20 — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Numbers 1-20" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtcco56lr', 'shapes-vocabulary-pack-k-2-en-es', 'Shapes — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Shapes" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtc8s9laz', 'animals-vocabulary-pack-k-2-en-es', 'Animals — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Animals" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtcdg6gl2', 'food-vocabulary-pack-k-2-en-es', 'Food — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Food" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtcm6x8el', 'family-members-vocabulary-pack-k-2-en-es', 'Family Members — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Family Members" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtc5nvz0f', 'body-parts-vocabulary-pack-k-2-en-es', 'Body Parts — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Body Parts" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtcltfgpy', 'weather-and-seasons-vocabulary-pack-k-2-en-es', 'Weather & Seasons — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Weather & Seasons" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtcw8ye9o', 'clothes-vocabulary-pack-k-2-en-es', 'Clothes — Vocabulary Pack (K-2, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Clothes" — designed for K-2 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtco9ek1l', 'classroom-furniture-classroom-labels-k-2-en-es', 'Classroom Furniture — Classroom Labels (K-2, EN-ES)', 'Bilingual classroom labels in full-size and small formats for "Classroom Furniture" — print, cut, and display in your K-2 classroom. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtc9770bn', 'school-supplies-classroom-labels-k-2-en-es', 'School Supplies — Classroom Labels (K-2, EN-ES)', 'Bilingual classroom labels in full-size and small formats for "School Supplies" — print, cut, and display in your K-2 classroom. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtcvxyojn', 'classroom-areas-classroom-labels-k-2-en-es', 'Classroom Areas — Classroom Labels (K-2, EN-ES)', 'Bilingual classroom labels in full-size and small formats for "Classroom Areas" — print, cut, and display in your K-2 classroom. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtcxhgyqb', 'days-and-months-classroom-labels-k-2-en-es', 'Days & Months — Classroom Labels (K-2, EN-ES)', 'Bilingual classroom labels in full-size and small formats for "Days & Months" — print, cut, and display in your K-2 classroom. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtcb9zcph', 'time-and-clock-classroom-labels-k-2-en-es', 'Time & Clock — Classroom Labels (K-2, EN-ES)', 'Bilingual classroom labels in full-size and small formats for "Time & Clock" — print, cut, and display in your K-2 classroom. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtc0vuwb8', 'basic-greetings-sentence-frames-k-2-en-es', 'Basic Greetings — Sentence Frames (K-2, EN-ES)', 'Bilingual sentence frame cards, dialogue strips, speaking prompts, and writing practice for "Basic Greetings" — designed for K-2 ELL newcomers. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtcmgu5ux', 'asking-for-help-sentence-frames-k-2-en-es', 'Asking for Help — Sentence Frames (K-2, EN-ES)', 'Bilingual sentence frame cards, dialogue strips, speaking prompts, and writing practice for "Asking for Help" — designed for K-2 ELL newcomers. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtctxql0r', 'expressing-feelings-sentence-frames-k-2-en-es', 'Expressing Feelings — Sentence Frames (K-2, EN-ES)', 'Bilingual sentence frame cards, dialogue strips, speaking prompts, and writing practice for "Expressing Feelings" — designed for K-2 ELL newcomers. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtciyw9yx', 'classroom-instructions-sentence-frames-k-2-en-es', 'Classroom Instructions — Sentence Frames (K-2, EN-ES)', 'Bilingual sentence frame cards, dialogue strips, speaking prompts, and writing practice for "Classroom Instructions" — designed for K-2 ELL newcomers. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtcpseiga', 'sharing-and-taking-turns-sentence-frames-k-2-en-es', 'Sharing & Taking Turns — Sentence Frames (K-2, EN-ES)', 'Bilingual sentence frame cards, dialogue strips, speaking prompts, and writing practice for "Sharing & Taking Turns" — designed for K-2 ELL newcomers. English-Spanish.', 'single', 399, 'standard', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtcp8cwob', 'science-vocabulary-vocabulary-pack-3-5-en-es', 'Science Vocabulary — Vocabulary Pack (3-5, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Science Vocabulary" — designed for 3-5 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtcd5hue4', 'math-vocabulary-vocabulary-pack-3-5-en-es', 'Math Vocabulary — Vocabulary Pack (3-5, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Math Vocabulary" — designed for 3-5 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtc1tgso5', 'social-studies-vocabulary-pack-3-5-en-es', 'Social Studies — Vocabulary Pack (3-5, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Social Studies" — designed for 3-5 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtc3qard8', 'reading-and-writing-vocabulary-pack-3-5-en-es', 'Reading & Writing — Vocabulary Pack (3-5, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Reading & Writing" — designed for 3-5 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 899, 'premium', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtcckzdlk', 'health-and-safety-vocabulary-pack-3-5-en-es', 'Health & Safety — Vocabulary Pack (3-5, EN-ES)', 'Print-ready bilingual vocabulary cards, matching worksheets, tracing activities, and a mini-book for "Health & Safety" — designed for 3-5 ELL newcomers and bilingual classrooms. English-Spanish.', 'single', 599, 'plus', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtcfcfg4y', 'academic-discussion-sentence-frames-3-5-en-es', 'Academic Discussion — Sentence Frames (3-5, EN-ES)', 'Bilingual sentence frame cards, dialogue strips, speaking prompts, and writing practice for "Academic Discussion" — designed for 3-5 ELL newcomers. English-Spanish.', 'single', 899, 'premium', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtc9oqtgh', 'writing-prompts-and-responses-sentence-frames-3-5-en-es', 'Writing Prompts & Responses — Sentence Frames (3-5, EN-ES)', 'Bilingual sentence frame cards, dialogue strips, speaking prompts, and writing practice for "Writing Prompts & Responses" — designed for 3-5 ELL newcomers. English-Spanish.', 'single', 899, 'premium', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtcf9hg92', 'welcome-letter-parent-communication-k-2-en-es', 'Welcome Letter — Parent Communication (K-2, EN-ES)', 'Bilingual parent communication templates for "Welcome Letter" — ready to print and send home. Covers English and Spanish for K-2 classrooms.', 'single', 399, 'standard', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtc9cyyn6', 'homework-note-parent-communication-k-2-en-es', 'Homework Note — Parent Communication (K-2, EN-ES)', 'Bilingual parent communication templates for "Homework Note" — ready to print and send home. Covers English and Spanish for K-2 classrooms.', 'single', 399, 'standard', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtcsjoh61', 'progress-report-parent-communication-k-2-en-es', 'Progress Report — Parent Communication (K-2, EN-ES)', 'Bilingual parent communication templates for "Progress Report" — ready to print and send home. Covers English and Spanish for K-2 classrooms.', 'single', 399, 'standard', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');

-- === Bundles (3) ===
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtc0xs6aj', 'newcomer-starter-kit-bundle-en-es', 'Newcomer Starter Kit', 'Everything a newcomer student needs in their first weeks: classroom objects, colors, numbers, basic greetings, and asking for help. 5 printable packs, English-Spanish.', 'bundle', 1499, 'mini_bundle', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtcdscknw', 'classroom-essentials-labels-bundle-en-es', 'Classroom Essentials — Labels & Signs', 'Set up your bilingual classroom with all 5 label packs: furniture, supplies, areas, days & months, and time. Print, cut, and display. English-Spanish.', 'bundle', 1499, 'mini_bundle', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtcihxpzy', 'complete-k5-ell-pack-bundle-en-es', 'Complete K-5 ELL Teaching Pack', 'All 30 printable teaching packs in one bundle — vocabulary, labels, sentence frames, and parent communication for K-5 ELL and bilingual classrooms. English-Spanish. Best value.', 'bundle', 2999, 'full_bundle', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');

-- === Membership (1) ===
INSERT INTO products (id, slug, name, description, type, price_cents, price_tier, active, created_at, updated_at) VALUES ('prod_mmh6njtcyhm3x2', 'all-access-membership', 'LanternELL All Access', 'Unlimited downloads of every pack in the LanternELL library. New packs added regularly. Cancel anytime.', 'membership', 900, 'monthly', 1, '2026-03-08 03:18:42.958', '2026-03-08 03:18:42.958');

-- === Bundle Resource Links ===
-- Bundle: Newcomer Starter Kit
-- product_resources link: bundle prod_mmh6njtc0xs6aj -> single pack prod_mmh6njtbujutwl (Classroom Objects)
-- product_resources link: bundle prod_mmh6njtc0xs6aj -> single pack prod_mmh6njtc22xiry (Colors)
-- product_resources link: bundle prod_mmh6njtc0xs6aj -> single pack prod_mmh6njtcfoujlk (Numbers 1-20)
-- product_resources link: bundle prod_mmh6njtc0xs6aj -> single pack prod_mmh6njtc0vuwb8 (Basic Greetings)
-- product_resources link: bundle prod_mmh6njtc0xs6aj -> single pack prod_mmh6njtcmgu5ux (Asking for Help)
-- Bundle: Classroom Essentials — Labels & Signs
-- product_resources link: bundle prod_mmh6njtcdscknw -> single pack prod_mmh6njtco9ek1l (Classroom Furniture)
-- product_resources link: bundle prod_mmh6njtcdscknw -> single pack prod_mmh6njtc9770bn (School Supplies)
-- product_resources link: bundle prod_mmh6njtcdscknw -> single pack prod_mmh6njtcvxyojn (Classroom Areas)
-- product_resources link: bundle prod_mmh6njtcdscknw -> single pack prod_mmh6njtcxhgyqb (Days & Months)
-- product_resources link: bundle prod_mmh6njtcdscknw -> single pack prod_mmh6njtcb9zcph (Time & Clock)
-- Bundle: Complete K-5 ELL Teaching Pack
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtbujutwl (Classroom Objects)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtc22xiry (Colors)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtcfoujlk (Numbers 1-20)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtcco56lr (Shapes)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtc8s9laz (Animals)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtcdg6gl2 (Food)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtcm6x8el (Family Members)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtc5nvz0f (Body Parts)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtcltfgpy (Weather & Seasons)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtcw8ye9o (Clothes)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtco9ek1l (Classroom Furniture)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtc9770bn (School Supplies)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtcvxyojn (Classroom Areas)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtcxhgyqb (Days & Months)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtcb9zcph (Time & Clock)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtc0vuwb8 (Basic Greetings)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtcmgu5ux (Asking for Help)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtctxql0r (Expressing Feelings)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtciyw9yx (Classroom Instructions)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtcpseiga (Sharing & Taking Turns)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtcp8cwob (Science Vocabulary)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtcd5hue4 (Math Vocabulary)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtc1tgso5 (Social Studies)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtc3qard8 (Reading & Writing)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtcckzdlk (Health & Safety)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtcfcfg4y (Academic Discussion)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtc9oqtgh (Writing Prompts & Responses)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtcf9hg92 (Welcome Letter)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtc9cyyn6 (Homework Note)
-- product_resources link: bundle prod_mmh6njtcihxpzy -> single pack prod_mmh6njtcsjoh61 (Progress Report)

COMMIT;

-- ============================================
-- Summary:
--   Single packs: 30
--   Bundles: 3
--   Membership: 1
--   Total products: 34
-- ============================================
--
-- Price tier distribution (single packs):
--   plus: 12 packs × $5.99 = 71.88 total value
--   standard: 15 packs × $3.99 = 59.85 total value
--   premium: 3 packs × $8.99 = 26.97 total value